name: Docker Build & Trivy Scan

on:
  push:
    branches:
      - main  # Runs the workflow when pushing to the main branch
  pull_request:
    branches:
      - main

jobs:
  setup-and-build:
    name: Setup Docker & Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Verify Docker Installation
        run: docker --version

      - name: Build Docker Image
        run: docker build -t flask-app:latest .

  security-scan:
    name: Scan Docker Image with Trivy
    needs: setup-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.45.0_Linux-64bit.tar.gz
          tar -xzvf trivy_0.45.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Docker Image
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL flask-app:latest
